name: mtw_app
description: Mapping the World is a project about explorers, cartographers and their maps.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  vector_math: ^2.1.4
  google_fonts: ^5.1.0
  rive: ^0.11.4
  go_router: ^9.0.3
  url_launcher: ^6.1.12

dependency_overrides:
  http: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  test: ^1.24.1

flutter:
  uses-material-design: true
  assets:
    - assets/
